#!/usr/bin/env bash
#Script displays infinity and beyond indefinitely
while :                                            
do                                                 
        echo "I am alive!" >> /tmp/my_process      
        sleep 2                                    
done
